chore: stop duplicate CI runs on branches
ApeWorX/ape pull request #1004
Opened 2022-08-19 00:36 UTC by fubuloubu

### What I did
Stop running CI twice

2022-08-19 13:08 UTC, unparalleled-js approved these changes
Do we need to do the same for the lint checks?

So it was only running twice when the user pushed their branch to the ApeWorX org, right (just making sure I am followin)?

2022-08-19 13:28 UTC, unparalleled-js commented
I think the tests may not be running

2022-08-19 18:21 UTC, unparalleled-js requested changes
I don't think this will work, the logic seems off.

However, I think we can do this:

```yaml
  push:
    branches:
      - 'main'
```

and now it will only run on pushes to main instead of pushing to branches

2022-08-19 21:03 UTC, unparalleled-js commented
I'm trying it on hardhat now: https://github.com/ApeWorX/ape-hardhat/pull/92/files

2022-08-20 14:45 UTC, fubuloubu commented
> I don't think this will work, the logic seems off.
> 
> However, I think we can do this:
> 
> ```yaml
>   push:
>     branches:
>       - 'main'
> ```
> 
> and now it will only run on pushes to main instead of pushing to branches
> 
> Edit: this goes in the `on` section at the top. You can make it an object rather than a list of strings

The idea behind not restricting other branches is that in a fork, someone can just enable github actions (and add their secrets) and it should function there too, for heavier development

2022-09-02 20:02 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            == github.event.pull_request.base.repo.full_name
```suggestion
            github.event_name == "push"
            && github.repository_owner != "ApeWorX"
```

2022-09-02 20:02 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            == github.event.pull_request.base.repo.full_name
```suggestion
            github.event_name == "push"
            && github.repository_owner != "ApeWorX"
```

2022-09-02 20:02 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            == github.event.pull_request.base.repo.full_name
```suggestion
            github.event_name == "push"
            && github.repository_owner != "ApeWorX"
```

2022-09-02 20:02 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            == github.event.pull_request.base.repo.full_name
```suggestion
            github.event_name == "push"
            && github.repository_owner != "ApeWorX"
```

2022-09-02 20:04 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            && github.repository_owner != "ApeWorX"
```suggestion
            github.event_name == "pull_request"
            || github.repository_owner != "ApeWorX"
```

2022-09-02 20:04 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            && github.repository_owner != "ApeWorX"
```suggestion
            github.event_name == "pull_request"
            || github.repository_owner != "ApeWorX"
```

2022-09-02 20:04 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            && github.repository_owner != "ApeWorX"
```suggestion
            github.event_name == "pull_request"
            || github.repository_owner != "ApeWorX"
```

2022-09-02 20:04 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            && github.repository_owner != "ApeWorX"
```suggestion
            github.event_name == "pull_request"
            || github.repository_owner != "ApeWorX"
```

2022-09-02 20:08 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            || github.repository_owner != "ApeWorX"
```suggestion
        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```

2022-09-02 20:08 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            || github.repository_owner != "ApeWorX"
```suggestion
        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```

2022-09-02 20:08 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            || github.repository_owner != "ApeWorX"
```suggestion
        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```

2022-09-02 20:08 UTC, fubuloubu commented on .github/workflows/test.yaml
> +            || github.repository_owner != "ApeWorX"
```suggestion
        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```

2022-09-02 20:36 UTC, unparalleled-js submitted a review, later dismissed
LGTM

to translate, actions will run either if it's a PR (no matter if from fork or not) or if it is a push to a fork. 

Thus, a push to ApeWorX/ape won't trigger unless it's on a PR
Thus, there are no more duplicate CI runs on branches pushed to ApeWorX/ape.

2022-09-02 21:46 UTC, fubuloubu commented
> LGTM
> 
> to translate, actions will run either if it's a PR (no matter if from fork or not) or if it is a push to a fork. 
> 
> Thus, a push to ApeWorX/ape won't trigger unless it's on a PR
> Thus, there are no more duplicate CI runs on branches pushed to ApeWorX/ape.

Yeah, still not quite perfect (would prefer branches to run if and only if they are not in an active PR), but this is the best I can do.

I also am not a huge fan of how they say "ignored"

2022-09-02 21:47 UTC, fubuloubu commented
Also appears that linting, type checking, and fuzzing didn't trigger...

2022-09-06 21:28 UTC, fubuloubu reviewed
Don't need the escapes with `if`

2022-09-06 21:28 UTC, fubuloubu commented on .github/workflows/test.yaml
> +        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```suggestion
        if: github.event_name == "pull_request" || github.repository_owner != "ApeWorX"
```

2022-09-06 21:28 UTC, fubuloubu commented on .github/workflows/test.yaml
> +        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```suggestion
        if: github.event_name == "pull_request" || github.repository_owner != "ApeWorX"
```

2022-09-06 21:28 UTC, fubuloubu commented on .github/workflows/test.yaml
> +        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```suggestion
        if: github.event_name == "pull_request" || github.repository_owner != "ApeWorX"
```

2022-09-06 21:28 UTC, fubuloubu commented on .github/workflows/test.yaml
> +        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'ApeWorX' }}
```suggestion
        if: github.event_name == "pull_request" || github.repository_owner != "ApeWorX"
```

2022-12-01 01:13 UTC, unparalleled-js commented
See https://github.com/ApeWorX/ape/pull/1171, including the stackoverflow link

2022-12-01 04:36 UTC, closed without merging