feat: added test 1
ApeWorX/ape pull request #1175
Opened 2022-12-06 21:00 UTC by Ninjagod1251

### What I did
Add test for ape-230

fixes: # Ape-354

### How I did it
created a test file in `tests/integration/cli/test_init.py`

### How to verify it
run the test

I would like some help:

- verify the project name in ape-config.yaml

2022-12-07 00:56 UTC, sabotagebeats requested changes
There are some things keeping the test from working

2022-12-07 01:02 UTC, sabotagebeats requested changes
When I did these things I was able to get this test to pass

2022-12-07 01:02 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    project_folder = Path.cwd()
```suggestion
    project_folder = Path.cwd()
    os.system('rm -rf ./* && rm .gitignore')
```

2022-12-07 01:02 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    assert "n.env" in git_ignore_file.read_text()
```suggestion
```

2022-12-07 01:02 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    result = runner.invoke(["rm", "-rf"])
```suggestion
    os.system('rm -rf ./*') 
```

2022-12-07 01:02 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    assert not project_folder.exists()
```suggestion
    for folder_name in ["contracts", "tests", "scripts"]:
        # Create target Directory
        folder = project_folder / folder_name
        assert not folder.exists()
```

2022-12-07 01:07 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +
I'm not sure if we want to use `os.system` or some other mechanism.

2022-12-07 01:07 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    assert "n.env" in git_ignore_file.read_text()
`n.env` is an artifact from a newline

2022-12-07 01:08 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    project_folder = Path.cwd()
if you don't rm these files then there is some remaining from whatever project we are using already.

2022-12-07 01:08 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    result = runner.invoke(["rm", "-rf"])
runner invoke fails when you don't use it with `ape_cli`

2022-12-07 01:08 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    assert not project_folder.exists()
`project_folder` will exist since we are using `Path.cwd()`

2022-12-07 01:11 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +    result = runner.invoke(ape_cli, ["init"], input="init_success")
the `"\n".join` is necessary here because we use additional newlines to step through the input prompts

2022-12-07 01:20 UTC, sabotagebeats commented on tests/integration/cli/test_init.py
> +
if we don't want to use `os.system` we could use `shutil` like you did in `src/ape_init/_cli.py`

2022-12-09 20:08 UTC, Ninjagod1251 commented
ready for review @unparalleled-js and @sabotagebeats

2022-12-12 16:28 UTC, unparalleled-js reviewed
Could use a little tidying up, but the tests are nice!

2022-12-12 16:28 UTC, unparalleled-js commented on tests/integration/cli/test_init.py
> +    # failed to create a folder because it exist
```suggestion
    # failed to create all folders because they exist
```

2022-12-12 19:31 UTC, Ninjagod1251 commented on src/ape_init/_cli.py
> +            click.prompt(f"{project_name} is written in ape-config.yaml")
It didnt complain when i did pre-commit. I added a \n at the end of .yaml anyways :)
`click.prompt(f"{project_name} is written in ape-config.yaml\n")`

2022-12-12 19:34 UTC, unparalleled-js commented on src/ape_init/_cli.py
> +            click.prompt(f"{project_name} is written in ape-config.yaml")
No, I mean at the end of the source file, not the prompt

2022-12-12 23:26 UTC, unparalleled-js approved these changes

2022-12-12 23:26 UTC, unparalleled-js commented on src/ape_init/_cli.py
> +            click.prompt(f"{project_name} is written in ape-config.yaml\n")
```suggestion
            cli_ctx.logger.success(f"{project_name} is written in ape-config.yaml")
```

2022-12-12 23:33 UTC, unparalleled-js submitted a review, later dismissed

2022-12-13 00:20 UTC, unparalleled-js submitted a review, later dismissed

2022-12-13 15:00 UTC, merged