fix: added notice
ApeWorX/ape pull request #1394
Opened 2023-04-20 22:13 UTC by Ninjagod1251

### What I did

Add the contributing notice from [Ape-90](https://github.com/ApeWorX/ape/issues/90)

fixes: #

### How I did it

### How to verify it

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

2023-04-20 23:25 UTC, fubuloubu submitted a review, later dismissed

2023-04-22 16:13 UTC, antazoey requested changes

2023-04-22 16:13 UTC, antazoey commented on CONTRIBUTING.md
> +##### NOTE: You might run into issues where you have a local install and are trying to work with a plugin pinned to a specific version.
this is the wrong number of `#`

2023-04-22 16:13 UTC, antazoey commented on CONTRIBUTING.md
> +##### NOTE: You might run into issues where you have a local install and are trying to work with a plugin pinned to a specific version.
`#` is for titles, not notes.
For notes do this use the asterisks. (Look at other parts of the docs with the bolded notes part.)

2023-04-22 16:13 UTC, antazoey commented on CONTRIBUTING.md
> +[The easy solution](https://github.com/ApeWorX/ape/issues/90) to this is simple fetch the tags via `git fetch upstream --tags` and reinstall via `pip install ..` You will then have the correct versio
1 sentence per line

2023-04-22 16:13 UTC, antazoey commented on CONTRIBUTING.md
> +[The easy solution](https://github.com/ApeWorX/ape/issues/90) to this is simple fetch the tags via `git fetch upstream --tags` and reinstall via `pip install ..` You will then have the correct versio
```suggestion
[The easiest solution](https://github.com/ApeWorX/ape/issues/90) to this is to fetch the tags via `git fetch upstream --tags` and reinstall via `pip install ..`.
You will then have the correct version.
```

2023-04-26 18:10 UTC, antazoey commented on CONTRIBUTING.md
> +[The easiest solution](https://github.com/ApeWorX/ape/issues/90) to this is to fetch the tags via `git fetch upstream --tags` and reinstall via `pip install ..`
```suggestion
[The easiest solution](https://github.com/ApeWorX/ape/issues/90) to this is to fetch the tags via `git fetch upstream --tags` and reinstall via `pip install .`. 
```

2023-04-26 18:12 UTC, antazoey approved these changes

2023-04-26 19:13 UTC, merged