Feat/ninjagod/contract fixture
ApeWorX/ape pull request #1395
Opened 2023-04-20 22:30 UTC by Ninjagod1251

### What I did

Started the Contract fixture implementation for [ape-1241](https://github.com/ApeWorX/ape/issues/1241)

fixes: #

### How I did it

### How to verify it

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

2023-04-20 23:24 UTC, fubuloubu commented on src/ape/pytest/fixtures.py
> +        return ContractInstance.address()
Look at where `ape.Contract` comes from

2023-04-26 18:23 UTC, antazoey reviewed
@NotPeopling2day is helping!!

2023-04-26 18:23 UTC, antazoey commented on src/ape/pytest/fixtures.py
> +    def on_chain_contract(ContractInstance):
arg name should be `self` not sure why you put `ContractInstance` here tbh

2023-04-26 18:23 UTC, antazoey commented on src/ape/pytest/fixtures.py
> +        return ContractInstance.address()
i dont think there is a class method `address` for ContractInstance, but if there was, that is not what we want here.

Return `self.chain_manager.instance_at` the method, the return type is a callable that takes an address and returns a `ContractInstance`

2023-04-26 18:23 UTC, antazoey commented on tests/conftest.py
> +@pytest.fixture(scope="session")
?

2023-04-26 19:29 UTC, antazoey reviewed
need test, see other fixture tests

2023-04-26 19:29 UTC, antazoey commented on src/ape/pytest/fixtures.py
> +    def on_chain_contract(self):
this need to be called `Contract` to align with `ape.Contract`

2023-04-26 19:29 UTC, antazoey commented on src/ape/pytest/fixtures.py
> +        Access contract types and dependencies.
```suggestion
        Instantiate a reference to an on-chain contract using its address (same as ``ape.Contract``).
```

2023-04-26 23:53 UTC, antazoey commented on tests/functional/test_contract_instance.py
> +def test_contract_fixture(contract_instance):
no this is not testing the fixture, you need to add an integration test.
add a test to this file instead: https://github.com/ApeWorX/ape/blob/main/tests/integration/cli/projects/test/tests/test_fixtures.py

2023-04-27 18:20 UTC, antazoey commented on src/ape/pytest/fixtures.py
> +    def contract(self):
do capital C

2023-04-27 18:42 UTC, antazoey commented on tests/functional/test_contract_instance.py
> +def test_use_contract(Contract, address):
ape fixtures are not available in core's tests like this, do remove this and only use the integration test

2023-04-27 18:42 UTC, antazoey commented on tests/integration/cli/projects/test/tests/test_fixtures.py
> +    assert isinstance(Contract, ContractInstance)
no this is callable, this test will fail (if you run it)...
you need to get an address from somewhere else and then `Contract(address)` will be the instance

2023-04-27 19:01 UTC, antazoey commented
probably should also mention this feature in the testing user guide

2023-05-03 18:28 UTC, antazoey requested changes
test does not test the newly added code.

2023-05-03 18:28 UTC, antazoey commented on tests/integration/cli/projects/test/tests/test_fixtures.py
> +def test_contract(accounts):
I dont see the `Contract` being used?
That is the fixture you are adding, that is what you should be testing.

2023-05-04 15:42 UTC, antazoey commented on tests/integration/cli/projects/test/tests/test_fixtures.py
> +    assert chain.contracts.instance_at == Contract
actual goes first

```suggestion
    assert Contract == chain.contracts.instance_at
```

2023-05-04 15:43 UTC, antazoey submitted a review, later dismissed

2023-05-04 15:44 UTC, antazoey commented
Thanks Ninja god, this is an excellent PR!

2023-05-04 16:46 UTC, fubuloubu approved these changes

2023-05-04 17:10 UTC, antazoey commented on tests/integration/cli/projects/test/tests/test_fixtures.py
> +from ape.contracts import ContractInstance
my bad, was trying to fix the commit history but messed it up

```suggestion
```

2023-05-04 17:38 UTC, merged