fix(networks): avoid persistent fork [APE-1030]
ApeWorX/ape pull request #1470
Opened 2023-06-08 14:03 UTC by fubuloubu

### What I did

When popping a provider off the stack, it should disconnect in order to reset the connection in scenarios where the provider is an ephemeral fork or locally provisioned network

fixes: #1433

### How I did it

Disconnect after popping a provider off the stack

### How to verify it

Noticing now that #933 made a change exactly counter to this, I am thinking that there is a relevant change necessary in `ape_test` that will make these both function properly together. Maybe the behavior should be configurable?

### Checklist

- [ ] Ensure that tests still function appropriately (test providers don't disconnect until the end of a test per #933)
- [ ] Ensure that console usage functions appropriately (repeated calls to `network.fork()` use fresh fork chain)
- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

2023-06-08 17:33 UTC, sabotagebeats approved these changes

2023-06-13 01:30 UTC, antazoey requested changes
@fubuloubu Disconnecting the provider will cause multi-network testing to not really work.
How else you can change the provider in tests if it disconnects?

Let's say i am running forked nodes across a bunch of live networks in my test suite... if i switch a provider from one to the next, it will disconnect the entire process.

So maybe a config option or something, but the caveat that you have to manage connections yourself or only use 1 provider.

2023-06-13 13:58 UTC, fubuloubu commented
> @fubuloubu Disconnecting the provider will cause multi-network testing to not really work. How else you can change the provider in tests if it disconnects?
> 
> Let's say i am running forked nodes across a bunch of live networks in my test suite... if i switch a provider from one to the next, it will disconnect the entire process.
> 
> So maybe a config option or something, but the caveat that you have to manage connections yourself or only use 1 provider.

This is sort of a middle road of what we had before (disconnect and connect so only one connection is maintained at a time) and what we have now (leave everything connected until ape shuts down), the idea being that a connection stays connected as long as it's in the provider stack, and when it's popped off the stack have it disconnect only at that point

I do think some other broader updates are need to support this, but in my mind during testing the way it would work is:
1. connect to default/selected provider at startup
2. run each test (with snapshots)
3. if a provider connection marker is discovered, have it push and then pop when the test goes out of scope (actually kind of similar to how snapshots work)
4. disconnect from selected provider after tests are finished (have to stay connected during report collection and if user wants to debug)

2023-06-13 16:16 UTC, antazoey commented
If we disconnect, there is no point to even having a network stack.

```python
def test_multichain(provider, networks):
    # Do initial bridge set up
    <stuff>
    
    # Connect to other network and do stuff
   with networks.other.local.use_provider("test"):
       <stuff>

   # !!!!!! Now, the rest of ALLL tests will fail because there is no more connected provider.

```

2023-06-13 16:26 UTC, antazoey commented
How can I deploy a contract in a sessional fixture if popping disconnects?

2023-06-13 16:28 UTC, antazoey commented
Show me a project that uses multichain testing in fixtures, individual tests per each network, and tests that switch networks mid test... if all three of the use-cases are fulfilled, we can move forward.

2023-06-13 19:34 UTC, fubuloubu commented
> How can I deploy a contract in a sessional fixture if popping disconnects?

The disconnect should happen after the session ends, agree with you there

If you temporarily connect in the middle of a test, it should disconnect at the end of the context manager's scope

I think overall there is some work needed to fix it to work properly under the variety of use cases that we support since the current way test fixtures work relies on this behavior that it never disconnects during the test session, which is hurting it's ability to be used for scripting (e.g. temporary fork to check the outcome of a transaction before commiting to broadcast it to public network)

2023-06-13 20:09 UTC, antazoey commented
@fubuloubu Awesome. OK, we can definitely make both use-cases happy, just will need some craftiness

2023-06-13 22:42 UTC, fubuloubu commented
> @fubuloubu Awesome. OK, we can definitely make both use-cases happy, just will need some craftiness

Exactly!

2023-09-15 20:08 UTC, antazoey commented
so that out multi-chain testing features continue to work, i suggest a solution like this: https://github.com/ApeWorX/ape/pull/1664

which treats the `fork()` method a little differently and actually disconnects in these scenarios, as that seems more fitting for that use-case.

2023-09-15 20:33 UTC, fubuloubu commented
Closing in favor of #1664

2023-09-15 20:33 UTC, closed without merging