added docs for multicall
ApeWorX/ape pull request #1617
Opened 2023-08-22 23:28 UTC by Aviksaikat

### What I did

fixes: #1611

### How I did it

Added documentation for `multicall` ape plugin.

### How to verify it

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [x] Documentation has been updated

2023-08-25 16:25 UTC, antazoey requested changes
this needs another round of revising.

2023-08-25 16:25 UTC, antazoey commented on docs/methoddocs/plugins.md
> +#### Usage
In markdown, you need to only increase the number of `#` by one for each new hear.
The parent header has only two `#`s and you are going all the way up to four here.

2023-08-25 16:25 UTC, antazoey commented on docs/methoddocs/plugins.md
> +Ape comes with builtin `multicall` method. Yes you're reading this right. No need to install external modules to do multicall, ape got you covered.Perform the Multicall call. This call will trigger a
Most of the words in the sentence are superfluous. I think only the first one (slightly re-written) is ok here.

```
The `ape-ethereum` core plugin comes with a multi-call module.
```

In general, docs should be simple and informative and not have any marketing terms.

2023-08-25 18:27 UTC, Aviksaikat commented on docs/methoddocs/plugins.md
> +```js
To make the syntax highlighting cool

2023-08-25 18:29 UTC, Aviksaikat commented on docs/methoddocs/plugins.md
> +## Multicall
As `multicall` is under the `ape_ethereum` plugin I thought it should be under `plugins.md`. What do you think @fubuloubu ?

2023-08-25 18:37 UTC, antazoey commented on docs/methoddocs/plugins.md
> +## Multicall
The plugins guide is talk about the plugin system, not each individual plugin.
However, calling out that is from the ape-ethereum core plugin I think is important.

2023-08-25 22:03 UTC, Aviksaikat commented on docs/methoddocs/plugins.md
> +## Multicall
so should I put it in `transactions.md` ?

2023-08-25 22:10 UTC, Aviksaikat commented on docs/methoddocs/plugins.md
> +Raises:
Is it necessary? I can this repo https://github.com/banteg/multicall.py if you want

2023-08-28 14:44 UTC, antazoey commented on docs/methoddocs/plugins.md
> +## Multicall
Yes please.

2023-08-28 14:46 UTC, antazoey commented on docs/methoddocs/plugins.md
> +## Multicall
Or `contracts.md` in the contract-interaction section.
But this plugins guide is meant only for describing the plugin system to users.

2023-08-28 14:47 UTC, antazoey commented on docs/methoddocs/plugins.md
> +## Multicall
Actually--- this is not even the plugin's guide, this is the auto-generated method docs.
User guides should be in the user-guides.

2023-08-29 14:35 UTC, antazoey commented on docs/userguides/contracts.md
> +Encode the Multicall transaction as a ``TransactionAPI`` object, but do not execute it.
not sure why this comment out, i dont think we need this section anyway

2023-08-29 14:35 UTC, antazoey commented on docs/userguides/contracts.md
> +This is a sample example of how you can perform multicall in a real world scenario. This piece of code will perfrom multicall on a `Uniswap V2` pool contract.
1 sentence per line

2023-08-29 14:35 UTC, antazoey commented on docs/userguides/contracts.md
> +### Practical Example
This section should probably be at the end

2023-08-29 21:12 UTC, antazoey submitted a review, later dismissed

2023-08-29 21:12 UTC, antazoey commented on docs/userguides/contracts.md
> +This is a sample example of how you can perform multicall in a real world scenario.
```suggestion
This is an example of how you can perform multicall in a real world scenario.
```

2023-08-29 21:12 UTC, antazoey approved these changes

2023-08-29 21:12 UTC, antazoey commented on docs/userguides/contracts.md
> +Raises:
method docs shouldnt be here

2023-08-31 12:27 UTC, antazoey submitted a review, later dismissed
super close

2023-09-01 23:25 UTC, antazoey commented
closing for https://github.com/ApeWorX/ape/pull/1649

2023-09-01 23:25 UTC, closed without merging